filebeat.inputs:
  - type: log
    enabled: true
    paths:
      #- /var/log/*.log
      - C:\fundanalyzer\logs\*
      - C:\selenium\logs\*
      - C:\fundanalyzer\patch\logs\*
      - C:\fundanalyzer\patch\fundanalyzer-patch\logs\*

    json.keys_under_root: true
    json.overwrite_keys: true

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
