spring:
  profiles:
    # マージ前にテスト確認！！！
#    active: dev
      active: prod
  application:
    name: fundanalyzer

#logging:
#  file:
#    name: ${spring.application.name}
#    path: C:/${spring.application.name}/log/
logging:
  level:
    org.seasar.doma:
      jdbc:
        UtilLoggingJdbcLogger: WARN

app:
  settings:
    file:
      path:
        company: C:/${spring.application.name}/company/EdinetcodeDlInfo.csv
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  api:
    edinet: https://disclosure.edinet-fsa.go.jp
    slack: https://hooks.slack.com/services/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
