spring:
  profiles:
    active: dev
  #    active: prod
  application:
    name: fundanalyzer

edinet:
  api: https://disclosure.edinet-fsa.go.jp

settings:
  file:
    path:
      company: C:\${spring.application.name}\company\EdinetcodeDlInfo.csv
      edinet: C:\${spring.application.name}\edinet
      decode: C:\${spring.application.name}\decode
