server:
  port: 8889

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fundanalyzer
    username: sa
    password:
  h2:
    console:
      enabled: true
  thymeleaf:
    encoding: UTF-8

doma:
  dialect: h2
  naming: snake_upper_case

management:
  metrics:
    tags:
      application: ${spring.application.name}-dev

app:
  api:
    slack:
      base-uri: https://hooks.slack.com
      parameter:
        t: TKN2V6NQ4
        b: B01EYUAKEL8
        x: x
