server:
  port: 8890

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundanalyzer?serverTimezone=Asia/Tokyo
    username: fundanalyzer
    password: fundanalyzer
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 10000
      max-lifetime: 180000
      auto-commit: true

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/fundanalyzer?serverTimezone=Asia/Tokyo
    schemas: fundanalyzer
    user: fundanalyzer
    password: fundanalyzer
    baseline-on-migrate: false  # Flywayのマイグレーションスクリプトの実行バージョンを途中から始めるか否か
    # baseline-version: 1.0.0  # baseline-on-migrate が true の場合に開始するバージョン
    # baseline-description: Initial  # baseline-version で実施された場合に記録されるコメント
    locations: classpath:db/migration

  thymeleaf:
    encoding: UTF-8

doma:
  dialect: mysql
  naming: snake_upper_case

logging:
  level: info

management:
  metrics:
    tags:
      application: ${spring.application.name}-main

app:
  api:
    slack:
      base-uri: https://hooks.slack.com
      parameter:
        t: TKN2V6NQ4
        b: B01DFHHPE07
        x: x
