spring:
  profiles:
    # dev | prod
    active: dev
  application:
    name: fundanalyzer

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: web

#logging:
#  file:
#    name: ${spring.application.name}
#    path: C:/${spring.application.name}/log/
logging:
  level:
    org.seasar.doma:
      jdbc:
        UtilLoggingJdbcLogger: WARN

management:
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 400ms
    tags:
      application: ${spring.application.name}

app:
  config:
    rest-template:
      connect-timeout: 15000
      read-timeout: 300000
    executor:
      core-pool-size: 50
      queue-capacity: 50
      max-pool-size: 500
    view:
      document-type-code: 120,130  # 分析表示処理対象
      discount-rate: 170  # 以上を表示
      outlier-of-standard-deviation: 10000  # 除外する標準偏差の外れ値
      coefficient-of-variation: 0.6  # 以下を表示
      diff-forecast-stock: 100  # 株価予想と最新株価との差が100以上を表示
      edinet-list.size: 400  # 日間を表示
    scraping:
      document-type-code: 120,130,140,150  # スクレイピング処理対象
      no-industry: 銀行業,保険業  # 処理対象外
    stock:
      average-stock-price-for-last-days: 30  # 株価平均値の期間
      store-stock-price-for-last-days: 365  # 株価の保存期間

  settings:
    file:
      path:
        company:
          company: C:/${spring.application.name}/company
          zip: C:/${spring.application.name}/company/zip
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  api:
    edinet: https://disclosure.edinet-fsa.go.jp
    selenium: http://localhost:9001

  scheduler:
    hour:
      company: 12  # 時に処理実施
      stock: 13  # 時に処理実施
      analysis: 14  # 時に処理実施
      update-view: 21  # 時に処理実施
