spring:
  profiles:
    # マージ前にテスト確認！！！
#    active: dev
        active: prod
  application:
    name: fundanalyzer

#logging:
#  file:
#    name: ${spring.application.name}
#    path: C:/${spring.application.name}/log/
logging:
  level:
    org.seasar.doma:
      jdbc:
        UtilLoggingJdbcLogger: WARN

app:
  settings:
    file:
      path:
        company: C:/${spring.application.name}/company/EdinetcodeDlInfo.csv
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  api:
    edinet: https://disclosure.edinet-fsa.go.jp
    slack:
      base-uri: https://hooks.slack.com
      parameter:
        t: TKN2V6NQ4
        b: B01DFHHPE07
        x: x
