spring:
  profiles:
    # マージ前にテスト確認！！！
    active: dev
#    active: prod
  application:
    name: fundanalyzer

#logging:
#  file:
#    name: ${spring.application.name}
#    path: C:/${spring.application.name}/log/
logging:
  level:
    org.seasar.doma:
      jdbc:
        UtilLoggingJdbcLogger: WARN

app:
  settings:
    file:
      path:
        company:
          company: C:/${spring.application.name}/company
          zip: C:/${spring.application.name}/company/zip
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  api:
    edinet: https://disclosure.edinet-fsa.go.jp
    selenium: http://localhost:9001

  scheduler:
    cron:
      company: 0 0 12 * * *
      stock: 0 0 13 * * *
