server:
  port: 8889

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fundanalyzer;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  thymeleaf:
    encoding: UTF-8

  flyway:
    locations: classpath:/db/migration, classpath:/db/dataset

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=0s,recordStats

doma:
  dialect: h2
  naming: snake_upper_case

logging:
  level: debug
  config: classpath:log4j2-spring-dev.xml

management:
  server:
    port: 8989
  metrics:
    tags:
      application: ${spring.application.name}-dev

app:
  config:
    slack:
      parameter:
        t: TKN2V6NQ4
        b: B01EYUAKEL8
        x: x
