spring:
  profiles:
#    active: dev
      active: prod
  application:
    name: fundanalyzer

#logging:
#  file:
#    name: ${spring.application.name}
#    path: C:/${spring.application.name}/log/
logging:
  level:
    org.seasar.doma:
      jdbc:
        UtilLoggingJdbcLogger: WARN

edinet:
  api: https://disclosure.edinet-fsa.go.jp

settings:
  file:
    path:
      company: C:/${spring.application.name}/company/EdinetcodeDlInfo.csv
      edinet: C:/${spring.application.name}/edinet
      decode: C:/${spring.application.name}/decode
