server:
  port: 8890

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundanalyzer?serverTimezone=JST
    username: fundanalyzer
    password: fundanalyzer
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: UTF-8

doma:
  dialect: mysql
  naming: snake_upper_case

management:
  metrics:
    tags:
      application: ${spring.application.name}-main

app:
  api:
    slack:
      base-uri: https://hooks.slack.com
      parameter:
        t: TKN2V6NQ4
        b: B01DFHHPE07
        x: x
