spring:
  profiles:
    # dev | prod
    active: dev
  application:
    name: fundanalyzer

  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
    sender:
      type: web

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=5m,recordStats

#logging:
#  file:
#    name: ${spring.application.name}
#    path: C:/${spring.application.name}/log/
logging:
  level:
    org.seasar.doma:
      jdbc:
        UtilLoggingJdbcLogger: WARN

management:
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 400ms
    tags:
      application: ${spring.application.name}

app:
  config:
    rest-template:
      edinet:
        base-uri: https://disclosure.edinet-fsa.go.jp
        connect-timeout: 5s
        read-timeout: 60s
        max-attempts: 3
        back-off: 10s
      selenium:
        base-uri: http://localhost:9001
        connect-timeout: 5s
        read-timeout: 120s
        max-attempts: 3
        back-off: 60s
      slack:
        base-uri: https://hooks.slack.com
        connect-timeout: 5s
        read-timeout: 30s
        max-attempts: 3
        back-off: 5s

    executor:
      core-pool-size: 50
      queue-capacity: 50
      max-pool-size: 500

    view:
      document-type-code: 120,130  # 分析表示処理対象
      discount-rate: 170  # 以上を表示
      outlier-of-standard-deviation: 10000  # 除外する標準偏差の外れ値
      coefficient-of-variation: 0.6  # 以下を表示
      diff-forecast-stock: 100  # 株価予想と最新株価との差が100以上を表示
      corporate.size: 300  # 日間を表示
      edinet-list.size: 400  # 日間を表示

    scraping:
      document-type-code: 120,130,140,150  # スクレイピング処理対象
      no-industry: 銀行業,保険業  # 処理対象外
      no-company: E31748
      # 日本郵政株式会社

    stock:
      average-stock-price-for-last-days: 30  # 株価平均値の期間
      store-stock-price-for-last-days: 365  # 株価の保存期間

    remove-document:
      document-type-code: 140,150
      company: E03815,E03041,E01737,E34537,E33624,E01542,E33625,E03724,E02611,E05080,E00334,E00678,E01124,E00816,E05047,E00840
      # マネックスグループ株式会社,株式会社クレディセゾン,株式会社日立製作所,ポート株式会社,プレミアグループ株式会社,株式会社荏原製作所
      # アルヒ株式会社,Ｊトラスト株式会社,日本ユニシス株式会社,楽天グループ株式会社,日本ハム株式会社,ユニ・チャーム株式会社,ＨＯＹＡ株式会社
      # 協和キリン株式会社,株式会社リログループ,三井化学株式会社

  settings:
    file:
      path:
        company:
          company: C:/${spring.application.name}/company
          zip: C:/${spring.application.name}/company/zip
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  scheduler:
    hour:
      company: 12  # 時に処理実施
      stock: 13  # 時に処理実施
      analysis: 0  # 時に処理実施
      update-view: 2  # 時に処理実施
      recover-document-period: 1  # 時に処理実施

    analysis.past-days: 30  # 日間に遡って処理実施
    recover-document-period.past-days: 30  # 日間に遡って処理実施
