server.port: 8890

logging.level: info

app:
  config:
    rest-template:
      connect-timeout: 15000
      read-timeout: 300000
    executor:
      core-pool-size: 50
      queue-capacity: 50
      max-pool-size: 500
    view:
      discount-rate: 120  # 以上を表示
      outlier-of-standard-deviation: 10000  # 除外する標準偏差の外れ値
      coefficient-of-variation: 0.6  # 以下を表示

  settings:
    file:
      path:
        company:
          company: C:/${spring.application.name}/company
          zip: C:/${spring.application.name}/company/zip
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  api:
    edinet: https://disclosure.edinet-fsa.go.jp
    selenium: http://localhost:9001
    slack:
      base-uri: https://hooks.slack.com
      parameter:
        t: TKN2V6NQ4
        b: B01DFHHPE07
        x: x # 任意の値を設定

  scheduler:
    cron:
      company: 0 0 12 * * *
      stock: 0 30 12 * * *
      analysis: 0 0 14 * * *
      update-view: 0 0 21 * * *
