server.port: 8890

logging.level: info

app:
  config:
    rest-template:
      connect-timeout: 15000
      read-timeout: 300000
    executor:
      core-pool-size: 50
      queue-capacity: 50
      max-pool-size: 500
    view:
      discount-rate: 170  # 以上を表示
      outlier-of-standard-deviation: 10000  # 除外する標準偏差の外れ値
      coefficient-of-variation: 0.6  # 以下を表示

  settings:
    file:
      path:
        company:
          company: C:/${spring.application.name}/company
          zip: C:/${spring.application.name}/company/zip
        edinet: C:/${spring.application.name}/edinet
        decode: C:/${spring.application.name}/decode

  api:
    edinet: https://disclosure.edinet-fsa.go.jp
    selenium: http://localhost:9001
    slack:
      base-uri: https://hooks.slack.com
      parameter:
        t: TKN2V6NQ4
        b: B01DFHHPE07
        x: x # 任意の値を設定

  scheduler:
    hour:
      company: 12  # 時に処理実施
      stock: 13  # 時に処理実施
      analysis: 0  # 時に処理実施
      update-view: 2  # 時に処理実施
      recover-document-period: 1  # 時に処理実施

    analysis.past-days: 30  # 日間に遡って処理実施
    recover-document-period.past-days: 30  # 日間に遡って処理実施
